name: Trigger auto deployment for wordpress-app-application

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/wordpress-app-application-AutoDeployTrigger-4e3d9ef2-ad5a-4474-b0fd-f771f710d12e.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.WORDPRESSAPPAPPLICATION_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.WORDPRESSAPPAPPLICATION_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.WORDPRESSAPPAPPLICATION_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: github.com/Helper85
          registryUsername: ${{ secrets.WORDPRESSAPPAPPLICATION_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.WORDPRESSAPPAPPLICATION_REGISTRY_PASSWORD }}
          containerAppName: wordpress-app-application
          resourceGroup: mrg-wordpress-containerapps--20250429110745
          imageToBuild: github.com/Helper85/wordpress-app-application:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


